
services:

  georef:
    profiles:
      - georef
    image: nylon_georef:dev
    entrypoint:
      - uvicorn
      - auto_georef.http.api:api
      - --host
      - "0.0.0.0"
      - --port
      - "3000"
      - --log-config
      - logging.yaml
      - --workers
      - "1"
      - "--reload"
    ports:
      - "3000:3000"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"
    networks:
      - nylon

