
version: '3'

services:
  baseline_mpm:
    profiles:
      - baseline_mpm
    image: baseline_mpm:dev
    entrypoint:
      - uvicorn
      - baseline_mpm.http.api:api
      - --host
      - "0.0.0.0"
      - --port
      - "4000"
      - --log-config
      - logging.yaml
      - --workers
      - "1"
      - "--reload"
    ports:
      - "4000:4000"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"


