name: Build Release

on:
  schedule:
    - cron: '0 10 * * 2'

  workflow_dispatch:


jobs:

  release:
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHP_ACCESS_TOKEN }}

      - name: Current Version
        run: make print-version

      - name: Increment Version
        run: make bump-version

      - name: Add New Version to env
        run: |
          set -xov
          echo "BUMP_VERSION=$(make print-version)" >> $GITHUB_ENV

      - name: git update version
        env:
          new_branch: version/${{ env.BUMP_VERSION }}
          GH_TOKEN: ${{ secrets.GHP_ACCESS_TOKEN }}
        run: |
          git config --global user.name "jatautomoton"
          git config --global user.email "jatautomoton@users.noreply.github.com"
          git checkout -b "${new_branch}"
          git add -u
          git diff --staged
          git commit -m "version ${{ env.BUMP_VERSION }}"

      - name: Building Version
        run: make print-version

      - name: Build docker containers
        run: make docker_buildx-all
        env:
          GITLAB_PASS: ${{ secrets.GITLAB_PASS }}
          GITLAB_USER: ${{ secrets.GITLAB_USER }}
          MAPTILER_KEY: ${{ secrets.MAPTILER_KEY }}

      - name: git create pr
        env:
          new_branch: version/${{ env.BUMP_VERSION }}
          GH_TOKEN: ${{ secrets.GHP_ACCESS_TOKEN }}
        run: |
          git push --set-upstream origin "${new_branch}"
          gh pr create --title "Version Bump: v${{ env.BUMP_VERSION }}" --body "Version: ${{ env.BUMP_VERSION }}"

      - name: git merge pr
        env:
          new_branch: version/${{ env.BUMP_VERSION }}
          GH_TOKEN: ${{ secrets.GHP_ACCESS_TOKEN }}
        run: |
          gh pr merge -s

      - name: git publish release
        env:
          GH_TOKEN: ${{ secrets.GHP_ACCESS_TOKEN }}
        run: |
          git fetch origin master
          gh release create "v${{ env.BUMP_VERSION }}" -t "Version: ${{ env.BUMP_VERSION }}" --generate-notes --latest --target master



